# Sample config to reproduce zero-shot results with FlanT5-xxl
# Usage example:
# 1 GPU: accelerate launch run.py --config configs/zero-shot/FlanT5-xxl.yaml
# Multi-GPU: accelerate launch --multi_gpu --num_processes 2 --main_process_port 29503 run.py --config configs/zero-shot/FlanT5-xxl.yaml

#Model args
model_name_or_path: google/flan-t5-xxl
torch_dtype: "float32"
quantization: 8
force_auto_device_map: false
predict_with_generate: false
per_device_eval_batch_size: 32
use_flash_attention: false
fewshot: false

# dataset arguments
do_train: false
do_eval: false
do_predict: true
do_predict_full_dataset: false
max_seq_length: 512

# Output Dir
output_dir: results/zero-shot/flan-t5-xxl


