#Model args
model_name_or_path: google/flan-t5-xxl
torch_dtype: "float32"
quantization: 8
predict_with_generate: false
per_device_eval_batch_size: 32
conversation_template: null

# dataset arguments
do_train: false
do_eval: false
do_predict: true
do_predict_full_dataset: false
max_seq_length: 512


# Output Dir
output_dir: results/zero-shot/flan-t5-xxl


